### ISSUE TITLE
install fails on node 8 + npm 5

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io-modules/resin-components#15]
node sass is failing see here: https://github.com/sass/node-sass/issues/1991 the said it should be fixed with npm 5.0.2 but travis still fails with that for now I'm locking the ci to node 7.

**Comment by probinsonsky** [comment]
Downgrading to Node 7 worked for me, thanks for the tip.
Followed these instructions:
https://stackoverflow.com/questions/7718313/how-to-change-to-an-older-version-of-node-js#23569481
