### ISSUE TITLE
Change typings to allow Modal title to be an element

### ISSUE THREAD

**Issue by thgreasi** [resin-io-modules/resin-components#183]
Currently `<Modal title={<h1>Title</h1>}>...</Modal>` works but the typings prohibit it.
This might not be straight-forward since the DefaultProps interface already contains `title?: string` and we can't override that.
Some possible "fixes" would be:
* remove the `title` from the DefaultProps interface
* create a `title-element` property

**Comment by thgreasi** [comment]
@LucianBuzzo What would you suggest?

**Comment by LucianBuzzo** [comment]
@thgreasi Let's change the name of this property to `titleElement`

**Comment by thgreasi** [comment]
@LucianBuzzo Should we fallback to the existing `title` (which is a semantic enough HTML attribute) when `titleElement` isn't defined, in an attempt to avoid the breaking change? We can deprecate `title` and remove it completely in v2.
OR should we do the breaking change right away an bump the version to v2?

**Comment by thgreasi** [comment]
Alternatively we could use a completely different property name like `header` or even use CSS to style the first `<header>` element of the modal's children.

**Comment by LucianBuzzo** [comment]
@thgreasi  Lets fall back to the title attribute if titleElement isn't available, so we can avoid a breaking change :+1:
