### ISSUE TITLE
Provide a way to set the (min-)widths of the Filter sub-components

### ISSUE THREAD

**Issue by thgreasi** [resin-io-modules/resin-components#208]
Now that Button min-width isn't used, we should provide a way to manipulate the button widths otherwise host projects will not be able to align things properly.
![screenshot-2017-12-5 resin io](https://user-images.githubusercontent.com/1295829/33613221-b75fa77e-d9dc-11e7-9c21-722871e3d0e5.png)

See: https://www.flowdock.com/app/rulemotion/resin-frontend/threads/wbkfrXc517e3Zx6harkn59v_u7b

**Comment by LucianBuzzo** [comment]
I suggest that we add an optional property on the HOC that allows you to set properties on the sub-components.
```
<Filters
    ...
    topLeftButtonProps={{ w: 30, mr: 20 }} />
```

**Comment by thgreasi** [comment]
:+1: 
Will that be typed as [`StyledSystemProps`](https://github.com/resin-io-modules/resin-components/blob/c70b1be24c67f522aac1bf86cfa9bd90412b9a52/typings.d.ts#L6) or do we need something broader?

**Comment by LucianBuzzo** [comment]
I think we'd just use `ButtonProps` here
