### ISSUE TITLE
Add husky precommit hook

### ISSUE THREAD

**Issue by LucianBuzzo** [resin-io-modules/resin-components#24]
The precommit should run lint and prettier.

**Comment by ethanent** [comment]
You should use [hitched](https://github.com/ethanent/hitched) instead of husky. [This article](https://github.com/ethanent/hitched/blob/master/docs/migrating.md) explains why! (It's about speed and efficiency!)

**Comment by LucianBuzzo** [comment]
resolved by https://github.com/resin-io-modules/resin-components/pull/35
