### ISSUE TITLE
`publish-storybook` script is failing

### ISSUE THREAD

**Issue by LucianBuzzo** [resin-io-modules/resin-components#47]
Uglify JS is unable to parse an arrow function imported into the bundle from resin-semver
```
Failed to build the storybook
static/preview.8657f91df26baa59b122.bundle.js from UglifyJs
Unexpected token: operator (>) [static/preview.8657f91df26baa59b122.bundle.js:76641,30]
```

**Comment by craig-mulligan** [comment]
This is because uglifyjs doesn't support es6, though it should be transpiled before by the babel loader before it hits the plugins.

**Comment by LucianBuzzo** [comment]
@craig-mulligan Yep that's what I've seen, except for whatever reason it's not transpiling required modules. There's an open issue about this https://github.com/storybooks/storybook/issues/1570

**Comment by craig-mulligan** [comment]
Ah the world of babel presets. Let me take a quick look otherwise we can merge #48
